image: gitpod/workspace-python

tasks:
  - init: |
      pip install -r requirements.txt
    command: |
      echo "🎯 Cambridge Exam System ready!"
      echo "Run: python main_gui_complete.py"

ports:
  - port: 8000
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - ms-python.pylint