name: Build Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --windowed --name "Cambridge-Exam-System" main_gui_complete.py
        
    - name: Build with PyInstaller (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        pyinstaller --onefile --windowed --name "Cambridge-Exam-System" main_gui_complete.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cambridge-exam-system-${{ matrix.os }}
        path: dist/